name: Docker Publish

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Inject GitHub Environment
        uses: rlespinasse/github-slug-action@v2.x
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build & Push the Docker image
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          image_name: bobbybeat1/cupsd
          image_tag: latest,${{ env.GITHUB_SHA_SHORT }}
          pull_image_and_stages: false
          push_git_tag: true
          context: "./cups"
